name: Release

concurrency: 
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Versioning and Github Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Release
        uses: python-semantic-release/python-semantic-release@v9
        id: release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          build: false
          vcs_release: true
  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python (via uv)
        run: uv python install

      - name: Set up virtualenv
        run: uv venv

      - name: Build
        run: uv build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  deploy:
    name: Deploy to PyPi
    runs-on: ubuntu-latest
    needs: build 
    environment:
      name: pypi
      url: https://pypi.org/p/witchat
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup | Download Build Artifacts
        uses: actions/download-artifact@v4
        id: artifact-download
        with:
          name: dist
          path: dist/


      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          print-hash: true
          verbose: true
